name: Examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Add rtcv_scraper_client to path
      run: go install

    - name: Set up Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.16

    - name: Run Deno example
      run: deno run -A examples/deno/main.ts
